import type { DefaultTheme } from 'vitepress'

const moduleGroup = (
  number: string,
  title: string,
  slug: string
): DefaultTheme.SidebarItem => ({
  text: `${number} · ${title}`,
  collapsed: true,
  items: [
    { text: '专题说明', link: `/modules/${slug}/README` }
  ]
})

export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    text: '训练入口',
    collapsed: false,
    items: [
      { text: '项目说明', link: '/README' },
      { text: '开始刷题', link: '/START_HERE' },
      { text: '完整学习路线', link: '/ROADMAP' }
    ]
  },
  moduleGroup('01', '复杂度与解题流程', '01-complexity'),
  moduleGroup('02', '数组、字符串与双指针', '02-array-string'),
  moduleGroup('03', '链表', '03-linked-list'),
  moduleGroup('04', '栈、队列与哈希', '04-stack-queue-hash'),
  moduleGroup('05', '二叉树与递归', '05-tree-recursion'),
  moduleGroup('06', '图、搜索与并查集', '06-graph-search'),
  moduleGroup('07', '动态规划与贪心', '07-dp-greedy'),
  moduleGroup('08', '综合面试模式', '08-interview-patterns'),
  {
    text: '题目与题单',
    collapsed: true,
    items: [
      { text: '题目索引', link: '/problems/README' },
      { text: '001 两数之和', link: '/problems/001-two-sum' },
      { text: '002 两数相加', link: '/problems/002-add-two-numbers' },
      { text: '003 无重复字符的最长子串', link: '/problems/003-longest-substring-without-repeating-characters' },
      { text: '004 寻找两个正序数组的中位数', link: '/problems/004-median-of-two-sorted-arrays' },
      { text: '005 最长回文子串', link: '/problems/005-longest-palindromic-substring' },
      { text: '015 三数之和', link: '/problems/015-three-sum' },
      { text: '019 删除链表的倒数第 N 个结点', link: '/problems/019-remove-nth-node-from-end-of-list' },
      { text: '020 有效的括号', link: '/problems/020-valid-parentheses' },
      { text: '021 合并两个有序链表', link: '/problems/021-merge-two-sorted-lists' },
      { text: '022 括号生成', link: '/problems/022-generate-parentheses' },
      { text: '023 合并 K 个升序链表', link: '/problems/023-merge-k-sorted-lists' },
      { text: '024 两两交换链表中的节点', link: '/problems/024-swap-nodes-in-pairs' },
      { text: '025 K 个一组翻转链表', link: '/problems/025-reverse-nodes-in-k-group' },
      { text: '032 最长有效括号', link: '/problems/032-longest-valid-parentheses' },
      { text: '033 搜索旋转排序数组', link: '/problems/033-search-in-rotated-sorted-array' },
      { text: '034 查找元素的第一个和最后一个位置', link: '/problems/034-find-first-and-last-position-of-element-in-sorted-array' },
      { text: '042 接雨水', link: '/problems/042-trapping-rain-water' },
      { text: '043 字符串相乘', link: '/problems/043-multiply-strings' },
      { text: '046 全排列', link: '/problems/046-permutations' },
      { text: '053 最大子数组和', link: '/problems/053-maximum-subarray' },
      { text: '054 螺旋矩阵', link: '/problems/054-spiral-matrix' },
      { text: '056 合并区间', link: '/problems/056-merge-intervals' },
      { text: '064 最小路径和', link: '/problems/064-minimum-path-sum' },
      { text: '069 x 的平方根', link: '/problems/069-sqrtx' },
      { text: '070 爬楼梯', link: '/problems/070-climbing-stairs' },
      { text: '072 编辑距离', link: '/problems/072-edit-distance' },
      { text: '075 颜色分类', link: '/problems/075-sort-colors' },
      { text: '076 最小覆盖子串', link: '/problems/076-minimum-window-substring' },
      { text: '078 子集', link: '/problems/078-subsets' },
      { text: '079 单词搜索', link: '/problems/079-word-search' },
      { text: '082 删除排序链表中的重复元素 II', link: '/problems/082-remove-duplicates-from-sorted-list-ii' },
      { text: '088 合并两个有序数组', link: '/problems/088-merge-sorted-array' },
      { text: '092 反转链表 II', link: '/problems/092-reverse-linked-list-ii' },
      { text: '093 复原 IP 地址', link: '/problems/093-restore-ip-addresses' },
      { text: '094 二叉树的中序遍历', link: '/problems/094-binary-tree-inorder-traversal' },
      { text: '101 对称二叉树', link: '/problems/101-symmetric-tree' },
      { text: '102 二叉树的层序遍历', link: '/problems/102-binary-tree-level-order-traversal' },
      { text: '103 二叉树的锯齿形层序遍历', link: '/problems/103-binary-tree-zigzag-level-order-traversal' },
      { text: '104 二叉树的最大深度', link: '/problems/104-maximum-depth-of-binary-tree' },
      { text: '105 从前序与中序遍历构造二叉树', link: '/problems/105-construct-binary-tree-from-preorder-and-inorder-traversal' },
      { text: '121 买卖股票的最佳时机', link: '/problems/121-best-time-to-buy-and-sell-stock' },
      { text: '122 买卖股票的最佳时机 II', link: '/problems/122-best-time-to-buy-and-sell-stock-ii' },
      { text: '124 二叉树中的最大路径和', link: '/problems/124-binary-tree-maximum-path-sum' },
      { text: '135 分发糖果', link: '/problems/135-candy' },
      { text: '139 单词拆分', link: '/problems/139-word-break' },
      { text: '141 环形链表', link: '/problems/141-linked-list-cycle' },
      { text: '142 环形链表 II', link: '/problems/142-linked-list-cycle-ii' },
      { text: '143 重排链表', link: '/problems/143-reorder-list' },
      { text: '146 LRU 缓存', link: '/problems/146-lru-cache' },
      { text: '148 排序链表', link: '/problems/148-sort-list' },
      { text: '152 乘积最大子数组', link: '/problems/152-maximum-product-subarray' },
      { text: '153 寻找旋转排序数组中的最小值', link: '/problems/153-find-minimum-in-rotated-sorted-array' },
      { text: '155 最小栈', link: '/problems/155-min-stack' },
      { text: '160 相交链表', link: '/problems/160-intersection-of-two-linked-lists' },
      { text: '165 比较版本号', link: '/problems/165-compare-version-numbers' },
      { text: '198 打家劫舍', link: '/problems/198-house-robber' },
      { text: '199 二叉树的右视图', link: '/problems/199-binary-tree-right-side-view' },
      { text: '200 岛屿数量', link: '/problems/200-number-of-islands' },
      { text: '206 反转链表', link: '/problems/206-reverse-linked-list' },
      { text: '207 课程表', link: '/problems/207-course-schedule' },
      { text: '209 长度最小的子数组', link: '/problems/209-minimum-size-subarray-sum' },
      { text: '215 数组中的第 K 个最大元素', link: '/problems/215-kth-largest-element-in-an-array' },
      { text: '221 最大正方形', link: '/problems/221-maximal-square' },
      { text: '224 基本计算器', link: '/problems/224-basic-calculator' },
      { text: '226 翻转二叉树', link: '/problems/226-invert-binary-tree' },
      { text: '230 二叉搜索树中第 K 小的元素', link: '/problems/230-kth-smallest-element-in-a-bst' },
      { text: '232 用栈实现队列', link: '/problems/232-implement-queue-using-stacks' },
      { text: '234 回文链表', link: '/problems/234-palindrome-linked-list' },
      { text: '236 二叉树的最近公共祖先', link: '/problems/236-lowest-common-ancestor-of-a-binary-tree' },
      { text: '239 滑动窗口最大值', link: '/problems/239-sliding-window-maximum' },
      { text: '240 搜索二维矩阵 II', link: '/problems/240-search-a-2d-matrix-ii' },
      { text: '287 寻找重复数', link: '/problems/287-find-the-duplicate-number' },
      { text: '300 最长递增子序列', link: '/problems/300-longest-increasing-subsequence' },
      { text: '322 零钱兑换', link: '/problems/322-coin-change' },
      { text: '328 奇偶链表', link: '/problems/328-odd-even-linked-list' },
      { text: '331 验证二叉树的前序序列化', link: '/problems/331-verify-preorder-serialization-of-a-binary-tree' },
      { text: '347 前 K 个高频元素', link: '/problems/347-top-k-frequent-elements' },
      { text: '394 字符串解码', link: '/problems/394-decode-string' },
      { text: '402 移掉 K 位数字', link: '/problems/402-remove-k-digits' },
      { text: '415 字符串相加', link: '/problems/415-add-strings' },
      { text: '416 分割等和子集', link: '/problems/416-partition-equal-subset-sum' },
      { text: '442 数组中重复的数据', link: '/problems/442-find-all-duplicates-in-an-array' },
      { text: '443 压缩字符串', link: '/problems/443-string-compression' },
      { text: '470 用 Rand7() 实现 Rand10()', link: '/problems/470-implement-rand10-using-rand7' },
      { text: '543 二叉树的直径', link: '/problems/543-diameter-of-binary-tree' },
      { text: '560 和为 K 的子数组', link: '/problems/560-subarray-sum-equals-k' },
      { text: '572 另一棵树的子树', link: '/problems/572-subtree-of-another-tree' },
      { text: '662 二叉树最大宽度', link: '/problems/662-maximum-width-of-binary-tree' },
      { text: '695 岛屿的最大面积', link: '/problems/695-max-area-of-island' },
      { text: '704 二分查找', link: '/problems/704-binary-search' },
      { text: '718 最长重复子数组', link: '/problems/718-maximum-length-of-repeated-subarray' },
      { text: '912 排序数组', link: '/problems/912-sort-an-array' },
      { text: '1143 最长公共子序列', link: '/problems/1143-longest-common-subsequence' },
      { text: '1262 可被三整除的最大和', link: '/problems/1262-greatest-sum-divisible-by-three' },
      {
        text: '原创面试题',
        collapsed: true,
        items: [
          { text: '原创 01 带过期时间的 LRU 缓存', link: '/problems/original-001-expiring-lru-cache' },
          { text: '原创题单 02 最小整数 I', link: '/problems/original-002-minimum-integer-i' },
          { text: '腾讯原创 03 蓄水池抽样', link: '/problems/original-003-reservoir-sampling' },
          { text: '腾讯原创 04 错排问题', link: '/problems/original-004-derangement' },
          { text: '腾讯原创 05 微信红包随机分配', link: '/problems/original-005-random-red-packet-allocation' },
          { text: '腾讯原创 06 单源最短路径', link: '/problems/original-006-single-source-shortest-path' },
          { text: '腾讯原创 07 迷宫最短路径', link: '/problems/original-007-maze-shortest-path' },
          { text: '腾讯原创 08 手写小根堆', link: '/problems/original-008-handwritten-min-heap' },
          { text: '腾讯原创 09 消消乐', link: '/problems/original-009-digit-elimination' }
        ]
      },
      { text: '题解模板', link: '/problems/TEMPLATE' },
      { text: '高频面试题单', link: '/tracks/top-interview' }
    ]
  },
  {
    text: '学习工作台',
    collapsed: true,
    items: [
      { text: '进度看板', link: '/progress/DASHBOARD' },
      { text: '解题笔记模板', link: '/notes/SOLUTION_NOTE_TEMPLATE' },
      { text: '内容规范', link: '/docs/CONTENT_STYLE_GUIDE' }
    ]
  }
]
